# EXP 01
## Git Bash Installation and Git Operations Steps:

### Installation of Git Bash and Demonstration of Basic Git Operations:

## Installation of Git Bash

### Step 1. Download Git from the official website: https://git-scm.com/downloads
### Step 2. Run the installer.
### Step 3. Select the default installation options.
### Step 4. Complete the installation.
### Step 5. Open **Git Bash** from the Start menu.
### Step 6. Verify the installation using:

#### git --version

### Example Output:
#### git version 2.xx.x.windows.x

## Procedure
### Step 1: Configure Git
#### git config --global user.name "Student Name"
#### git config --global user.email "student@example.com"

## Check the configuration:

#### git config --list

### Step 2: Create a New Repository

## Create a project folder.

#### mkdir StudentProject

## >> Move into the folder.

#### cd StudentProject


## >> Initialize Git.

#### ```bash
#### git init
#### ```

## >> Check the repository status.

#### ```bash
#### git status


### ---

### Step 3: Create a File

## >> Create a text file.

#### ```bash
#### echo "Hello Git" > file.txt


## >> View the repository status.

#### ```bash
#### git status


## ---

### Step 4: Add the File

## >> Stage the file.

#### ```bash
#### git add file.txt

## >> Check the status again.

#### ```bash
#### git status

## ---

### Step 5: Commit the File

## >> Create the first commit.

#### ```bash
#### git commit -m "Initial commit"

## >> View commit history.

#### ```bash
#### git log

## ---

### Step 6: Create a Branch

## >> Create a new branch.

#### ```bash
#### git branch feature

## >> Switch to the branch.

#### ```bash
#### git checkout feature

## --> Alternatively:

#### ```bash
#### git switch feature

## >> Verify the current branch.

#### ```bash
#### git branch

## ---

### Step 7: Modify the File

## >> Append text to the file.

#### ```bash
#### echo "This is feature branch." >> file.txt

## >> Stage and commit the changes.

#### ```bash
#### git add file.txt

#### >> git commit -m "Updated file in feature branch"

## ---

### Step 8: Merge the Branch

## >> Switch back to the main branch.

#### ```bash
#### git checkout main

## >> If your default branch is **master**, use:

#### ```bash
#### git checkout master

## >> Merge the feature branch.

#### ```bash
#### git merge feature

## ---

### Step 9: Verify the Merge

## >> View the commit history.

#### ```bash
#### git log --oneline --graph

## >> Display the file contents.

#### ```bash
#### cat file.txt


## --> Result

## --->The following Git operations were successfully performed:

### Git Bash installation
### Git configuration
### Repository creation
### File creation
### Staging files
### Committing changes
### Creating a branch
### Switching between branches
### Merging branches
### Viewing commit history

## Conclusion:

### The experiment demonstrated the installation and basic usage of Git Bash. A Git repository was created, files were added and committed, a new branch was created, changes were committed in the branch, and the branch was successfully merged into the main branch. These operations illustrate the fundamental concepts of version control using Git.

# EXP-02
## Write a Program to demonstrate Aggregate, Vectorized, Lmbda(), Map(), Reduce() and FIlter() Functions in Numpy:

#### What is an Aggregation Function?

#### An aggregation function takes many values and turns them into one single value.

#### Think of it like this: you have 100 numbers, and you want just ONE number that represents them all (like the total, or the average).

In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("Array:",a)
print("Sum:",np.sum(a))
print("Mean:",np.mean(a))
print("Maximum:",np.max(a))
print("Minimum:",np.min(a))
print("Standard Deviation:",np.std(a))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951

### What is a Vectorized Operation in Numpy?

#### A vectorized operation means: doing an action on an entire array/column at once, instead of using a loop to go through each value one by one.

#### Pandas and NumPy are built to handle whole columns in one shot — this is much faster than writing a for loop.
### Program to demonstrate Vectorized Operation in Numpy:

In [3]:
import numpy as np
marks=np.array([56,76,89,90,87,65])
print("Marks:",marks)
marks + 5

Marks: [56 76 89 90 87 65]

array([61, 81, 94, 95, 92, 70])

### Adding 10% to salary:

In [4]:
salary=np.array([10000,25000,35000,40000,57000])
print("Salary before adding 10%:",salary)
salary=salary*1.1
print("Salary after adding 10%:",salary)

Salary before adding 10%: [10000 25000 35000 40000 57000]
Salary after adding 10%: [11000. 27500. 38500. 44000. 62700.]

### Lambda Function in Numpy:

### What is a Lambda Function?

#### A lambda function is a small, one-line function that doesn't need a name. It's used when you need a quick function for a short task, without writing a full def function.

#### Also called: anonymous function (function without a name).
### Map Function with Numpy:

In [5]:
a=np.array([1,2,3,4,5])
res=list(map(lambda x: x*x,a))
print("Square values:",res)

Square values: [np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]

### Filter Function with Numpy:

In [47]:
res1=list(filter(lambda x: x > 3,a))
print("Values that are greater than 3:",res1)

Values that are greater than 3: [np.int64(4), np.int64(5)]

### Using lambda with Numpy:

In [48]:
res2=list(map(lambda x: x+5,a))
print("After adding 5 to all values:",res2)

After adding 5 to all values: [np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]

### Compare the execution time of a normal function (def) & a lambda function using the time module.

In [49]:
import time
def square(x):
    return x*x
square_lambda=lambda x: x*x
start=time.time()
for i in range(10):
    square(i)
end=time.time()
print("Normal Function time:",end-start)
square_lambda(i)
print("Lambda Function:",end-start)

Normal Function time: 0.0001423358917236328
Lambda Function: 0.0001423358917236328

### Reduce Function with Numpy:

### What is reduce()?

#### reduce() takes a list of values and combines them into a single value, by repeatedly applying a function on pairs of elements, one after another.

#### It "reduces" the whole list down to one final result.
## Program to demonstrate reduce() function in NUMPY:

In [50]:
import numpy as np
from functools import reduce
a1=np.array([10,20,30,40,50])
b=reduce(lambda x,y: x*y,a1)
print(b)

12000000

# EXP 03
## Aggregate Function (agg()) in PANDAS:
### Definition

### An aggregate function combines many values into one single result. It is used to calculate summaries like sum, average, minimum, maximum, and count.
## Write a Program to create dataframe and demonstrate Aggregate, Vectorized, Lmbda(), Map(), Reduce() and FIlter() Functions and also Grouping and Time series operations in PANDAS:

In [51]:
import pandas as pd

data = {
    "Marks": [80, 90, 70, 60]
}

df = pd.DataFrame(data)

print(df["Marks"].agg("sum"))

300

### Here, agg("sum") adds all the marks.

In [52]:
df["Marks"].agg("mean")

np.float64(75.0)

### Here,agg() used to Display Minimum,Maximum and Mean value:

In [53]:
df["Marks"].agg(["min", "max", "mean"])

min     60.0
max     90.0
mean    75.0
Name: Marks, dtype: float64

## Reduce Function in PANDAS:
### Definition

### A reduce function combines all values one by one and returns a single value.

### It is available in Python through the functools module.
## Program to demonstrate Reduce function in PANDAS:

In [54]:
from functools import reduce

numbers = [1, 2, 3, 4, 5]

result = reduce(lambda x, y: x + y, numbers)

print(result)

15

## Lambda Function in PANDAS:
### Definition

### A lambda function is a small anonymous function (a function without a name). It is useful when you need a short function for one-time use.
## Program to demonstrate Lambda function in PANDAS:

In [55]:
square = lambda x: x * x # Note series is created in previous example

print(square(5))

25

## Vectorization
### Definition

### Vectorization means performing an operation on an entire column or array at once, instead of using loops. It is faster and simpler.

## Program to demonstrate vectorization function in PANDAS:
### Before adding 5 marks to each students marks:

In [68]:
import pandas as pd
data={ 
    "Name":["Azhar","Aftoz","Rayan","Tarun","Hafeez","Junaid"],
    "Branch":["CS","EC","AT","CS","CP","CS"],
    "Age":[17,18,19,17,19,20],
    "Marks":[98,28,45,54,67,36] 
    }
df=pd.DataFrame(data)
df

     Name Branch  Age  Marks
0   Azhar     CS   17     98
1   Aftoz     EC   18     28
2   Rayan     AT   19     45
3   Tarun     CS   17     54
4  Hafeez     CP   19     67
5  Junaid     CS   20     36

### Ater adding Bonus 5 Marks to each students:

In [67]:
df["Bonus"] = df["Marks"] + 5
df

     Name Branch  Age  Marks  Bonus
0   Azhar     CS   17     98    103
1   Aftoz     EC   18     28     33
2   Rayan     AT   19     45     50
3   Tarun     CS   17     54     59
4  Hafeez     CP   19     67     72
5  Junaid     CS   20     36     41

## GROUPING IN PANDAS:
### What is Grouping?

#### Grouping means: split your data into categories, then do some calculation on each category separately.

#### Think of it like sorting students into different sections, then finding the average marks for each section — not the whole class together.
## Program to demonstrate Grouping in PANDAS:

In [59]:
import pandas as pd
data={ 
    "Name":["Azhar","Aftoz","Rayan","Tarun","Hafeez","Junaid"],
    "Branch":["CS","EC","AT","CS","CP","CS"],
    "Age":[17,18,19,17,19,20],
    "Marks":[98,28,45,54,67,36] 
    }
df=pd.DataFrame(data)
df

     Name Branch  Age  Marks
0   Azhar     CS   17     98
1   Aftoz     EC   18     28
2   Rayan     AT   19     45
3   Tarun     CS   17     54
4  Hafeez     CP   19     67
5  Junaid     CS   20     36

### Displaying the sum of the each branch marks:

In [60]:
c=df.groupby("Branch").agg(Sum_Marks=("Marks","mean")).reset_index().round(2)
print(c)

  Branch  Sum_Marks
0     AT      45.00
1     CP      67.00
2     CS      62.67
3     EC      28.00

### Displaying the Average(Mean) of Age and Marks:

In [61]:
d=df.groupby("Branch").agg(Mean_Age=("Age","mean"),Mean_Marks=("Marks","mean")).reset_index().round(2)
print(d)

  Branch  Mean_Age  Mean_Marks
0     AT      19.0       45.00
1     CP      19.0       67.00
2     CS      18.0       62.67
3     EC      18.0       28.00

## TIME SERIES OPERATIONS IN PANDAS:
### What is Time Series Data?

### Time series data = data that has a date or time attached to each row.

### Example: daily sales, hourly temperature, monthly revenue.
## Program to demonstrate Monthly Sales in PANDAS:

In [62]:
df2 = pd.DataFrame({
                    "Dates":["2024-01-01","2024-02-02","2024-01-03","2024-01-04","2024-02-05",
                             "2024-02-06","2024-03-07","2024-03-08","2024-01-09","2024-03-10"],
                    "Sales": [10,20,15,25,30,12,18,22,27,35],
                    "Month": ["JAN","FEB","JAN","JAN","FEB","FEB","MAR","MAR","JAN","MAR"],
                    "Profit": [10000,17000,21000,40000,27000,17000,30000,11000,23000,50000]
                   })
df2

        Dates  Sales Month  Profit
0  2024-01-01     10   JAN   10000
1  2024-02-02     20   FEB   17000
2  2024-01-03     15   JAN   21000
3  2024-01-04     25   JAN   40000
4  2024-02-05     30   FEB   27000
5  2024-02-06     12   FEB   17000
6  2024-03-07     18   MAR   30000
7  2024-03-08     22   MAR   11000
8  2024-01-09     27   JAN   23000
9  2024-03-10     35   MAR   50000

### To Displaying the total profit of each month by grouping the months:

In [69]:
tp=df2.groupby("Month")["Profit"].sum()
print(tp)

Month
FEB    61000
JAN    94000
MAR    91000
Name: Profit, dtype: int64